"""add gemini_usage_daily

Revision ID: 382465da66f2
Revises: d1b993f38b67
Create Date: 2026-08-18 22:52:03.979761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '382465da66f2'
down_revision: Union[str, Sequence[str], None] = 'd1b993f38b67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gemini_usage_daily',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('call_count', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gemini_usage_daily')
    # ### end Alembic commands ###
