"""baseline schema

Revision ID: d1b993f38b67
Revises: 
Create Date: 2026-08-18 22:50:47.379512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd1b993f38b67'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('posting_text_hash', sa.String(length=64), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('company', sa.Text(), nullable=True),
    sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('technologies', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('experience', sa.Text(), nullable=True),
    sa.Column('responsibilities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('qualifications', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_posting_text_hash'), 'jobs', ['posting_text_hash'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('hashed_password', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('user_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('source_document_path', sa.Text(), nullable=True),
    sa.Column('source_document_format', sa.Text(), nullable=True),
    sa.Column('layout_document', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('linkedin_url', sa.Text(), nullable=True),
    sa.Column('github_url', sa.Text(), nullable=True),
    sa.Column('portfolio_url', sa.Text(), nullable=True),
    sa.Column('headline', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('technical_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('soft_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('programming_languages', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('frameworks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('libraries', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('databases', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cloud_platforms', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('devops_tools', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_ml_tools', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('development_tools', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('languages', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('work_experience', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('education', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('projects', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('github_repositories', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('open_source_contributions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('certifications', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('awards', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('achievements', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('leadership_experience', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('volunteer_work', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('publications', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('interests', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('references', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recommendations_received', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('links', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=False)
    op.create_table('resume_versions',
    sa.Column('user_profile_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('matched_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('missing_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('added_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ats_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('report', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rendered_file_url', sa.Text(), nullable=True),
    sa.Column('rendered_file_format', sa.Text(), nullable=True),
    sa.Column('layout_preserved', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['user_profile_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_versions_job_id'), 'resume_versions', ['job_id'], unique=False)
    op.create_index(op.f('ix_resume_versions_user_profile_id'), 'resume_versions', ['user_profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resume_versions_user_profile_id'), table_name='resume_versions')
    op.drop_index(op.f('ix_resume_versions_job_id'), table_name='resume_versions')
    op.drop_table('resume_versions')
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_table('users')
    op.drop_index(op.f('ix_jobs_posting_text_hash'), table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
