import uuid
from typing import Literal

from pydantic import BaseModel, field_validator

from schemas.resume_layout import ContentPatch


class GenerateResumeRequest(BaseModel):
    user_profile_id: uuid.UUID
    job_id: uuid.UUID


class ResumeExperienceEntry(BaseModel):
    title: str | None = None
    company: str | None = None
    location: str | None = None
    start_date: str | None = None
    end_date: str | None = None
    bullets: list[str] = []


class ResumeProjectEntry(BaseModel):
    name: str | None = None
    description: str | None = None
    url: str | None = None
    technologies: list[str] = []
    bullets: list[str] = []


class ResumeEducationEntry(BaseModel):
    institution: str | None = None
    degree: str | None = None
    field: str | None = None
    start_date: str | None = None
    end_date: str | None = None
    grade: str | None = None
    achievements: list[str] = []


class ResumeCertificationEntry(BaseModel):
    name: str | None = None
    issuer: str | None = None
    date: str | None = None
    url: str | None = None


class ResumeSkillGroup(BaseModel):
    label: str
    items: list[str] = []


class OptimizedResume(BaseModel):
    name: str | None = None
    email: str | None = None
    phone: str | None = None
    headline: str | None = None
    summary: str | None = None
    links: dict[str, str] = {}
    skills: list[str] = []
    skill_groups: list[ResumeSkillGroup] = []
    experience: list[ResumeExperienceEntry] = []
    projects: list[ResumeProjectEntry] = []
    education: list[ResumeEducationEntry] = []
    certifications: list[ResumeCertificationEntry] = []
    awards: list[str] = []
    leadership: list[str] = []
    volunteering: list[str] = []
    publications: list[str] = []
    interests: list[str] = []
    references: list[str] = []
    # Plain-language explanation of what was emphasized/reworded and why —
    # generated by the same LLM call, not a second one, so it stays
    # consistent with what was actually changed.
    changes_summary: list[str] = []

    # This is the first point raw, untrusted LLM JSON is validated (see
    # services/llm_output.py) — the prompt doesn't explicitly instruct
    # "unknown arrays: []" the way the other agents' prompts do, so coerce
    # defensively rather than risk a ValidationError on a null array.
    @field_validator(
        "skills", "skill_groups", "experience", "projects", "education",
        "certifications", "awards", "leadership", "volunteering",
        "publications", "interests", "references", "changes_summary",
        mode="before",
    )
    @classmethod
    def _null_to_empty_list(cls, value: list | None) -> list:
        return value if value is not None else []

    @field_validator("links", mode="before")
    @classmethod
    def _null_to_empty_dict(cls, value: dict | None) -> dict:
        return value if value is not None else {}


class ChangeHighlight(BaseModel):
    """One grouped, section-level line in an OptimizationReport — the
    LLM-authored replacement for changes_summary's old per-block prose."""
    section: str
    summary: str
    impact: Literal["high", "medium", "low"]


class KeywordSkipReason(BaseModel):
    """Why a specific missing_keyword was deliberately not woven in."""
    keyword: str
    reason: str


class ProjectRankingEntry(BaseModel):
    """Why a project ranked where it did in the resume's Projects section —
    see relevance_ranker.rank_profile's ranking_reasons. matched_on is empty
    when the project ranked purely on tie-break (no real keyword overlap),
    not on genuine relevance."""
    name: str | None = None
    matched_on: list[str] = []


class OptimizationReport(BaseModel):
    """
    Everything about *how* the resume was optimized, as opposed to
    OptimizedResume which is the resume content itself. Only `highlights`
    and `keywords_skipped` require the model's judgment; every other field
    is derived deterministically in code from the same generation run (see
    resume_generation_agent.py), so counts/scores can't drift from what
    actually happened.
    """
    ats_score_before: float
    ats_score_after: float
    matched_keywords_before: int
    matched_keywords_after: int
    keywords_added: list[str] = []
    keywords_skipped: list[KeywordSkipReason] = []
    unused_candidate_skills: list[str] = []
    skills_reordered: bool = False
    summary_rewritten: bool = False
    experience_bullets_modified: int = 0
    projects_modified: int = 0
    highlights: list[ChangeHighlight] = []
    # Mean difflib.SequenceMatcher ratio across blocks the LLM actually
    # changed (None if nothing changed) — a rough, code-level signal for
    # "how much did wording actually move," independent of the model's own
    # highlights. See resume_generation_agent._rewrite_quality.
    rewrite_similarity_avg: float | None = None
    # block_ids flagged as claiming a newly-added keyword while staying
    # implausibly similar to their original wording — a likely
    # stitched-on-rather-than-woven-in rewrite. Informational, not blocking.
    rewrite_quality_issues: list[str] = []
    # Why each surviving project ranked where it did (see
    # relevance_ranker.rank_profile) — surfaced so "why this project and
    # not that one" has a real, visible answer.
    project_ranking: list[ProjectRankingEntry] = []


class OptimizationPatchResponse(BaseModel):
    """
    The optimization LLM's actual output contract: it only ever returns
    ContentPatch[] keyed by the block_ids it was given (see
    services/synthetic_profile_layout.py) — never a restructured resume
    object directly. A deterministic post-step (Patch Engine + flattening)
    reconstructs OptimizedResume's external shape from this. highlights and
    keywords_skipped are the model's own reasoning (see OptimizationReport);
    everything else in the final report is computed from patches, not asked
    of the model.
    """
    patches: list[ContentPatch]
    highlights: list[ChangeHighlight] = []
    keywords_skipped: list[KeywordSkipReason] = []


class ResumeGenerationResponse(BaseModel):
    ats_score: float
    matched_keywords: list[str]
    missing_keywords: list[str]
    # Which missing_keywords the optimization actually wove into the resume's
    # wording — see services/keyword_matcher.py::find_added_keywords. A
    # subset of missing_keywords, not a fourth independent category: still
    # "missing" from the candidate's structured profile skill lists, but now
    # truthfully present in the rendered text.
    added_keywords: list[str] = []
    optimized_resume: OptimizedResume
    # See OptimizationReport — before/after scores, change counts, and the
    # model's own grouped highlights/keyword-skip reasoning.
    report: OptimizationReport
    download_url: str
    # True when the candidate's own uploaded docx/pdf was edited in place
    # (docx_renderer_v2.py / pdf_renderer_v2.py); False when generation fell
    # back to the generic Jinja2/xhtml2pdf template — either because there
    # was no source document, or profile_layout_correlator.py's confidence
    # gate rejected the correlation this run produced.
    layout_preserved: bool = False
